credentials: &credentials
  adapter: mysql
  encoding: utf8
  username: root
  password: haxored
  pool: 5
  host: localhost
  socket: '/tmp/mysql.sock'

development:
  <<: *credentials
  database: twitter2rss_development

test:
  <<: *credentials
  database: twitter2rss_test
